version: "3.9"
volumes:
  db_data: {}
  wordpress_data: {}   
services:
  services:
  db:
    # other properties like image, environment etc
    volumes:
      - db_data:/var/lib/mysql
  wordpress:
    # other properties like image, ports, depends_on etc
    volumes:
      - wordpress_data:/var/www/html
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

       